language: ruby
sudo: false
cache: bundler
rvm:
  - 2.1
  - 2.2
gemfile:
  - Gemfile.rails3
  - Gemfile.rails41
  - Gemfile.rails42
  - Gemfile.rails50
matrix:
  allow_failures:
    - gemfile: Gemfile.rails50
      rvm: 2.1
